# Generated by Django 3.2.7 on 2021-10-20 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 20, 4, 16, 6, 60041, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
