# Generated by Django 3.2.7 on 2021-10-23 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 3, 4, 4, 962663, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
